[build]
  publish = "dist"
  command = "npm install --include=dev && npm run build"

[context.production.environment]
  NODE_VERSION = "18" 
[build.environment]
  NPM_FLAGS = "--no-corepack"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
