[build]
  base = "Frontend"
  publish = "dist"
  command = "npm ci && npm run build"  # Use npm ci for clean install

[context.production.environment]
  NODE_VERSION = "18" 
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
