[build]
  base = "Frontend"
  publish = "dist"
  command = "cd Frontend && npm install && npm run build"

[context.production.environment]
  NODE_VERSION = "18" 
[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
