http:
  routers:
    backend-router:
      rule: Host(`localhost`)
      service: backend-service
      entryPoints:
        - web

  services:
    backend-service:
      loadBalancer:
        servers:
          - url: "http://backend:8000"